it_task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task_manager.urls", namespace="task_manager")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

task_manager/urls.py
from django.urls import path

from task_manager.views import (
    index,
    TaskListView,
    WorkerListView,
    WorkerDetailView,
    TaskDetailView,
    WorkerCreateView,
    WorkerUpdateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskCreateView,
    assign_delete_worker_to_task,
    change_task_status,
    TaskTypeCreateView,
    PositionCreateView,
)

urlpatterns = [
    path("", index, name="index"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/worker-assign-delete/",
        assign_delete_worker_to_task,
        name="assign-delete-worker-to-task",
    ),
    path(
        "tasks/<int:pk>/change-task-status/",
        change_task_status,
        name="change-task-status",
    ),
    path(
        "tasks/task-type-create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create"
    ),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update"
    ),
    path(
        "workers/position-create/",
        PositionCreateView.as_view(),
        name="position-create"
    ),
]

app_name = "task_manager"

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/search_form.html
{% load crispy_forms_filters %}
<form action="" method="get" class="form-inline">
  {{ search_form|crispy }}
  <input type="submit" value="🔎" class="btn btn-info">
</form>

templates/includes/sidebar.html
<div class="d-flex flex-column flex-shrink-0 p-3 pt-1 bg-light h-100" style="width: 100%;">
  {% if user.is_authenticated %}
    <div class="d-flex align-items-center">
    <span class="material-symbols-outlined" style="margin-right: 0.5rem;">
      account_circle
    </span>
      <a href="{{ user.get_absolute_url }}"
         class="fs-4 mb-3 mb-md-0 me-md-auto text-dark text-decoration-none" style="font-size: 1.5rem;">{{ user.get_username }}</a>
    </div>
    <div class="d-flex align-items-center">
    <span class="material-symbols-outlined" style="margin-right: 0.5rem;">
      input
    </span>
      <a class="fs-5 mb-3 mb-md-0 me-md-auto text-dark text-decoration-none"
         href="{% url 'logout' %}?next={{ request.path }}" style="font-size: 1.5rem;">
        Logout
      </a>
    </div>
  {% else %}
    <div class="d-flex align-items-center">
    <span class="material-symbols-outlined" style="margin-right: 0.5rem;">
      input
    </span>
      <a class="fs-5 mb-3 mb-md-0 me-md-auto text-dark text-decoration-none"
         href="{% url 'login' %}?next={{ request.path }}" style="font-size: 1.5rem;">
        Login
      </a>
    </div>
  {% endif %}
  <hr class="w-100">
  {% with request.resolver_match.url_name as url_name %}
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="{% url 'task_manager:index' %}"
           class="nav-link {% if url_name == 'index' %}active{% else %}text-dark{% endif %}">Home</a>
      </li>
      <li>
        <a href="{% url 'task_manager:task-list' %}"
           class="nav-link {% if url_name == 'task-list' %}active{% else %}text-dark{% endif %}">All tasks</a>
      </li>
      <li>
        <a href="{% url 'task_manager:worker-list' %}"
           class="nav-link {% if url_name == 'worker-list' %}active{% else %}text-dark{% endif %}">All workers</a>
      </li>
    </ul>
  {% endwith %}
</div>