it_task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task_manager.urls", namespace="task_manager")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

task_manager/urls.py
from django.urls import path

from task_manager.views import (
    index,
    TaskListView,
    WorkerListView,
    WorkerDetailView,
    TaskDetailView,
    WorkerCreateView,
    WorkerUpdateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskCreateView,
    assign_delete_worker_to_task,
    change_task_status,
    TaskTypeCreateView,
    PositionCreateView,
)

urlpatterns = [
    path("", index, name="index"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/worker-assign-delete/",
        assign_delete_worker_to_task,
        name="assign-delete-worker-to-task",
    ),
    path(
        "tasks/<int:pk>/change-task-status/",
        change_task_status,
        name="change-task-status",
    ),
    path(
        "tasks/task-type-create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create"
    ),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update"
    ),
    path(
        "workers/position-create/",
        PositionCreateView.as_view(),
        name="position-create"
    ),
]

app_name = "task_manager"

task_manager/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Position(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Worker(AbstractUser):
    position = models.ForeignKey(
        Position,
        on_delete=models.SET_NULL,
        related_name="workers",
        null=True
    )

    class Meta:
        verbose_name = "worker"
        verbose_name_plural = "workers"

    def __str__(self):
        return (
            f"{self.get_full_name()}, "
            f"username: {self.username}, position: {self.position}"
        )

    def get_absolute_url(self):
        return reverse("task_manager:worker-detail", kwargs={"pk": self.pk})


class TaskType(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Task(models.Model):
    class Priority(models.TextChoices):
        URGENT = "U", "Urgent"
        HIGH = "H", "High"
        MEDIUM = "M", "Medium"
        LOW = "L", "Low"

    name = models.CharField(max_length=64)
    description = models.TextField()
    deadline = models.DateTimeField()
    is_completed = models.BooleanField()
    priority = models.CharField(
        max_length=6,
        choices=Priority.choices,
        default=Priority.MEDIUM
    )
    task_type = models.ForeignKey(
        TaskType,
        on_delete=models.SET_NULL,
        null=True
    )
    assignees = models.ManyToManyField(Worker, related_name="tasks")

    def __str__(self):
        return (
            f"Task: {self.name}, "
            f"status: {'Completed' if self.is_completed else 'In work'}, "
            f"priority: {self.priority}"
        )

task_manager/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.utils import timezone

from task_manager.models import Worker, Task, TaskType, Position


def validate_deadline(deadline):
    datetime_now = timezone.now()
    if deadline <= datetime_now:
        raise ValidationError(
            "Oops! This deadline is not realistic. Try picking another time."
        )

    return deadline


class TaskCreationForm(forms.ModelForm):
    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )
    deadline = forms.DateTimeField(
        help_text="year-moth-day 00:00:00",
        widget=forms.DateTimeInput(attrs={"class": "datetime-input"}),
        input_formats=["%Y-%m-%d %H:%M:%S"],
        validators=[validate_deadline],
    )

    class Meta:
        model = Task
        fields = "__all__"


class TaskUpdateForm(forms.ModelForm):
    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )
    deadline = forms.DateTimeField(
        help_text="year-moth-day 00:00:00",
        widget=forms.DateTimeInput(attrs={"class": "datetime-input"}),
        input_formats=["%Y-%m-%d %H:%M:%S"],
        validators=[validate_deadline],
    )

    class Meta:
        model = Task
        fields = "__all__"


class TaskSearchForm(forms.Form):
    task_type = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by task type"}),
    )


class TaskTypeCreationForm(forms.ModelForm):
    class Meta:
        model = TaskType
        fields = "__all__"


class WorkerCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "email",
            "position",
        )


class WorkerUpdateForm(forms.ModelForm):
    class Meta:
        model = Worker
        fields = [
            "first_name",
            "last_name",
            "email",
            "position",
        ]


class WorkerSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username"}),
    )


class PositionCreationForm(forms.ModelForm):
    class Meta:
        model = Position
        fields = "__all__"

task_manager/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from task_manager.forms import (
    WorkerSearchForm,
    WorkerCreationForm,
    WorkerUpdateForm,
    TaskUpdateForm,
    TaskSearchForm,
    TaskCreationForm,
    TaskTypeCreationForm,
    PositionCreationForm,
)
from task_manager.models import Task, Worker, TaskType, Position


@login_required
def index(request: HttpRequest) -> HttpResponse:
    """View function for the home page of the site."""

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_visits": num_visits + 1,
    }

    if Worker.objects.prefetch_related("tasks").filter(id=request.user.id, tasks__is_completed=False):
        worker_with_task_count = (
            Worker.objects.prefetch_related("tasks")
            .filter(id=request.user.id, tasks__is_completed=False)
            .annotate(tasks_count=Count("tasks"))
            .first()
        )
        context["num_tasks"] = worker_with_task_count.tasks_count
    else:
        context["num_tasks"] = 0

    return render(request, "task_manager/index.html", context=context)


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    queryset = Task.objects.select_related(
        "task_type"
    ).prefetch_related("assignees")
    ordering = ["deadline"]
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        task_type = self.request.GET.get("task_type", "")
        context["search_form"] = TaskSearchForm(
            initial={"task_type": task_type}
        )
        return context

    def get_queryset(self):
        queryset = Task.objects.all()
        form = TaskSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                task_type__name__icontains=form.cleaned_data["task_type"]
            )
        return queryset


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task
    queryset = Task.objects.select_related(
        "task_type"
    ).prefetch_related("assignees")


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskCreationForm
    success_url = reverse_lazy("task_manager:task-list")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskUpdateForm
    success_url = reverse_lazy("task_manager:task-list")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("task_manager:task-list")


@login_required
def change_task_status(request, pk):
    task = Task.objects.get(pk=pk)

    task.is_completed = not task.is_completed
    task.save()

    return HttpResponseRedirect(request.META.get("HTTP_REFERER", "/"))


@login_required
def assign_delete_worker_to_task(request: HttpRequest, pk: int) -> HttpResponse:
    worker = Worker.objects.get(id=request.user.id)
    if Task.objects.get(id=pk) in worker.tasks.all():
        worker.tasks.remove(pk)
    else:
        worker.tasks.add(pk)
    return HttpResponseRedirect(reverse_lazy("task_manager:task-detail", args=[pk]))


class TaskTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    template_name = "task_manager/task_type_form.html"
    form_class = TaskTypeCreationForm
    success_url = reverse_lazy("task_manager:task-list")


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    queryset = Worker.objects.select_related("position")
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = WorkerSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        queryset = Worker.objects.all()
        form = WorkerSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker
    queryset = Worker.objects.select_related(
        "position"
    ).prefetch_related("tasks")


class WorkerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Worker
    form_class = WorkerCreationForm
    success_url = reverse_lazy("task_manager:worker-list")


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerUpdateForm
    success_url = reverse_lazy("task_manager:index")


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    form_class = PositionCreationForm
    success_url = reverse_lazy("task_manager:worker-list")

templates/task_manager/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Task Manager Home</h1>
  <hr>
  <p>🥳🥳🥳Welcome to Best Task Manager Ever!🥳🥳🥳</p>
  <hr>
  <h3>⏰️You have {{ num_tasks }} task{{ num_tasks|pluralize }}⏰️</h3>
  <hr>
  <h1><b>HAVE A NICE DAY</b></h1>
  <hr>
  <p>You have checked your tasks
    {{ num_visits }} time{{ num_visits|pluralize }}
  </p>

{% endblock %}

templates/task_manager/position_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} position</h1>
  <form action="" method="post" class="col-10 col-lg-6 col-md-8" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task_manager/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Task</h1>
  <p>Are you sure, you want to delete the {{ task }}?</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
    <a href="{{ request.META.HTTP_REFERER }}"><input type="button" value="No"
                                                     class="btn btn-lights border border-primary"></a>
  </form>
{% endblock %}

templates/task_manager/task_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    <b>Task type:</b> {{ task.task_type }}<br>
    <b>Priority:</b> {{ task.get_priority_display }}<br>
    <b>Status:</b> {% if task.is_completed %} Done {% else %} In work {% endif %}
    <a href="{% url 'task_manager:task-update' pk=task.id %}">
      UPDATE
    </a>

  </h1>
  <hr>
  <h2>{{ task.name }} {% if task in user.tasks.all %}(My task){% endif %}</h2>

  <h4>Info:</h4>
  <ul style="list-style: none">
    <li><b>deadline:</b> {{ task.deadline }}</li>
    <li><b>description:</b> {{ task.description }}</li>
  </ul>
  <hr>

  <h3>Assignees:</h3>
  {% if request.user in task.assignees.all %}
    <a href="{% url 'task_manager:assign-delete-worker-to-task' pk=task.id %}" class="btn btn-danger link-to-page">
      Delete me from this task
    </a>
  {% else %}
    <a href="{% url 'task_manager:assign-delete-worker-to-task' pk=task.id %}" class="btn btn-primary link-to-page">
      Assign me to this task
    </a>
  {% endif %}

  {% if task.assignees %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>Position</th>
        <th>Full name</th>
        <th>Email</th>
      </tr>
      {% for assignee in task.assignees.all %}
        <tr>
          <td>{{ assignee.id }}</td>
          <td>
            <a href="{{ assignee.get_absolute_url }}">{{ assignee.username }} {% if user == assignee %}
              (Me){% endif %}</a>
          </td>
          <td>{{ assignee.position }}</td>
          <td>{{ assignee.get_full_name }}</td>
          <td>{{ assignee.email }}</td>
        </tr>
      {% endfor %}

    </table>
  {% endif %}
{% endblock %}

templates/task_manager/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" class="col-10 col-lg-6 col-md-8" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task_manager/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Task List
    <a href="{% url 'task_manager:task-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
    <a href="{% url 'task_manager:task-type-create' %}" class="btn btn-secondary link-to-page">
      Add task type
    </a>
  </h1>

  {% include "includes/search_form.html" %}
  <br>


  {% if task_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>Deadline</th>
        <th>Status</th>
        <th>Priority</th>
        <th>Task type</th>
        <th>Assignees</th>
        <th>UPDATE</th>
        <th>DELETE</th>
      </tr>
      {% for task in task_list %}
        <tr>
          <td>{{ task.id }}</td>
          <td><a href="{% url 'task_manager:task-detail' pk=task.id %}">{{ task.name }}</a></td>
          <td>{{ task.description }}</td>
          <td>{{ task.deadline }}</td>
          <td>
            <a href="{% url 'task_manager:change-task-status' pk=task.id %}">
              {% if task.is_completed %} Done {% else %} In work {% endif %}
            </a>
          </td>
          <td>{{ task.priority }}</td>
          <td>{{ task.task_type }}</td>
          <td>
            {% for assignee in task.assignees.all %}
              <span>{{ assignee.get_full_name }};</span>
            {% endfor %}
          </td>
          <td>
            <a href="{% url 'task_manager:task-update' pk=task.id %}">
              UPDATE
            </a>
          </td>
          <td>
            <a style="color: red"
               href="{% url 'task_manager:task-delete' pk=task.id %}">
              DELETE
            </a>
          </td>
        </tr>
      {% endfor %}

    </table>
  {% else %}
    <p>There are no task for now.</p>
  {% endif %}
{% endblock %}

templates/task_manager/task_type_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task type</h1>
  <form action="" method="post" class="col-10 col-lg-6 col-md-8" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task_manager/worker_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ worker.get_full_name }}
    {% if worker.id == user.id %}
      (Me)
      <a href="{% url 'task_manager:worker-update' pk=worker.id %}">
        Update
      </a>
    {% endif %}
  </h1>

  <h4>Info:</h4>
  <ul style="list-style: none">
    <li><b>username:</b> {{ worker.username }}</li>
    <li><b>position:</b> {{ worker.position }}</li>
    <li><b>email:</b> {{ worker.email }}</li>
  </ul>

  <h3>Tasks:</h3>
  {% if worker.tasks.all %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Type</th>
        <th>Priority</th>
        <th>Deadline</th>
        <th>Status</th>
      </tr>
      {% for task in worker.tasks.all %}
        <tr>
          <td>{{ task.id }}</td>
          <td><a href="{% url 'task_manager:task-detail' pk=task.id %}">{{ task.name }}</a></td>
          <td>{{ task.task_type }}</td>
          <td>{{ task.priority }}</td>
          <td>{{ task.deadline }}</td>
          <td>
            <a href="{% url 'task_manager:change-task-status' pk=task.id %}">
              {% if task.is_completed %} Done {% else %} In work {% endif %}
            </a>
          </td>
        </tr>
      {% endfor %}

    </table>
  {% else %}
    <h6>No tasks</h6>
  {% endif %}
{% endblock %}

templates/task_manager/worker_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} worker</h1>
  <form action="" method="post" class="col-10 col-lg-6 col-md-8" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task_manager/worker_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Workers List
  </h1>
  <a href="{% url 'task_manager:worker-create' %}" class="btn btn-primary link-to-page mb-2">
    Create
  </a>
  <a href="{% url 'task_manager:position-create' %}" class="btn btn-secondary link-to-page mb-2">
    Add position
  </a>

  {% include "includes/search_form.html" %}
  <br>


  {% if worker_list %}
    <table class="table table-striped w-75">
      <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Username</th>
        <th scope="col">Position</th>
        <th scope="col">Full name</th>
        <th scope="col">Email</th>
      </tr>
      </thead>
      {% for worker in worker_list %}
        <tr>
          <td>{{ worker.id }}</td>
          <td>
            <a href="{{ worker.get_absolute_url }}">{{ worker.username }} {% if user == worker %} (Me){% endif %}</a>
          </td>
          <td>{{ worker.position }}</td>
          <td>{{ worker.get_full_name }}</td>
          <td>{{ worker.email }}</td>
        </tr>
      {% endfor %}

    </table>
  {% else %}
    <p>There are no workers now.</p>
  {% endif %}
{% endblock %}